version: "3.7"
# Template for common deploy options
x-deploy: &deploy-replicated
  mode: replicated
  replicas: 1
  placement:
    constraints:
      - node.role == manager
  resources:
    limits:
      memory: 128M
    reservations:
      memory: 64M
# Template for common deploy labels
x-deploy-labels: &deploy-labels
  - traefik.enable=true
  - traefik.tags=traefik-prod 
  - traefik.docker.network=traefik

networks:
  default:
    driver: overlay
  traefik:
    external: true

volumes:
    prometheus: {}
    grafana: {}
    alertmanager: {}

configs:
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yml
  websites_rules:
    file: ./prometheus/rules/websites.yml
  sites_rules:
    file: ./prometheus/rules/sites.yml
  blackbox_config:
    file: ./blackbox-exporter/conf/blackbox.yml

services:
  cadvisor:
    image: google/cadvisor:latest
    networks:
      - default
    command: -logtostderr -docker_only
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /:/rootfs:ro
      - /var/run:/var/run
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      <<: *deploy-replicated
      mode: global # overriding the value of mode from template

  grafana:
    image: dhileepbalaji/grafana:latest
    networks:
      - default
      - traefik
    environment:
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - GF_USERS_ALLOW_SIGN_UP=false
      #- GF_SERVER_ROOT_URL=${GF_SERVER_ROOT_URL:-localhost}
    volumes:
      - grafana:/var/lib/grafana
    deploy:
      <<: *deploy-replicated
      labels:
        <<: *deploy-labels
        - "traefik.http.routers.grafana.rule=Host(`grafana.example.com`)"
        #- traefik.http.routers.grafana.middlewares=oauth01
        - traefik.http.routers.grafana.entrypoints=prodhttps
        - traefik.http.routers.grafana.service=prom
        - traefik.http.services.grafana.loadbalancer.server.port=3000
        #- traefik.http.routers.grafana.tls=true
        #- traefik.http.routers.grafana.tls.certresolver=letsencrypt


  alertmanager:
    image: dhileepbalaji/alertmanager:latest
    networks:
      - default
      - traefik
    environment:
      - SLACK_URL=${SLACK_URL:-https://hooks.slack.com/services/TOKEN}
      - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
      - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    deploy:
      <<: *deploy-replicated
      labels:
        <<: *deploy-labels
        - "traefik.http.routers.alertmanager.rule=Host(`alertmanager.example.com`)"
        #- traefik.http.routers.alertmanager.middlewares=oauth01
        - traefik.http.routers.alertmanager.entrypoints=prodhttps
        - traefik.http.routers.alertmanager.service=prom
        - traefik.http.services.alertmanager.loadbalancer.server.port=9093
        #- traefik.http.routers.alertmanager.tls=true
        #- traefik.http.routers.alertmanager.tls.certresolver=letsencrypt

  unsee:
    image: cloudflare/unsee:v0.8.0
    networks:
      - default
      - traefik
    environment:
      - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      <<: *deploy-replicated
      labels:
        <<: *deploy-labels
        - "traefik.http.routers.unsee.rule=Host(`unsee.example.com`)"
        #- traefik.http.routers.unsee.middlewares=oauth01
        - traefik.http.routers.unsee.entrypoints=prodhttps
        - traefik.http.routers.unsee.service=prom
        - traefik.http.services.unsee.loadbalancer.server.port=8080
        #- traefik.http.routers.unsee.tls=true
        #- traefik.http.routers.unsee.tls.certresolver=letsencrypt

  node-exporter:
    image: dhileepbalaji/node-exporter:latest
    networks:
      - default
    environment:
      - NODE_ID={{.Node.ID}}
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /etc/hostname:/etc/nodename
    command:
      - '--path.sysfs=/host/sys'
      - '--path.procfs=/host/proc'
      - '--collector.textfile.directory=/etc/node-exporter/'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
      - '--no-collector.ipvs'
    deploy:
      <<: *deploy-replicated
      mode: global # overriding the value of mode from template


  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    networks:
      - default
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    configs:
      - source: blackbox_config
        target: /etc/blackbox_exporter/config.yml
    deploy:
      <<: *deploy-replicated


  prometheus:
    image: dhileepbalaji/prometheus:latest
    networks:
      - default
      - traefik
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention=${PROMETHEUS_RETENTION:-24h}'
    volumes:
      - prometheus:/prometheus
    configs:
      - source: node_rules
        target: /etc/prometheus/swarm_node.rules.yml
      - source: task_rules
        target: /etc/prometheus/swarm_task.rules.yml
      - source: sites_rules
        target: /etc/prometheus/sites.yml
      - source: websites_rules
        target: /etc/prometheus/websites.yml       
    deploy:
      <<: *deploy-replicated
      labels:
        <<: *deploy-labels
        - "traefik.http.routers.prom.rule=Host(`prometheus.example.com`)"
        - traefik.http.routers.prom.entrypoints=prodhttps
        #- traefik.http.routers.prom.middlewares=oauth01
        - traefik.http.routers.prom.service=prom
        - traefik.http.services.prom.loadbalancer.server.port=9090
        #- traefik.http.routers.prom.tls=true
        #- traefik.http.routers.unsee.tls.certresolver=letsencrypt

