groups:
    - name: websites
      rules:
      - alert: ProbeFailed
        expr: probe_success == 0
        for: 2m
        labels:
          severity: error
        annotations:
          description: "Site is Down {{ $labels.instance }} \n"
          summary: "Site Down\n"
      
      - alert: HttpStatusCode
        expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
        for: 2m
        labels:
          severity: error
        annotations:
          description: "HTTP status code Non-200X for {{ $labels.instance }} \n"
          summary: "HTTP Non-200X response \n"
      
      - alert: SslCertificateWillExpireSoon
        expr: probe_ssl_earliest_cert_expiry - time() < 86400 * 30
        for: 2m
        labels:
          severity: warning
        annotations:
          description: "SSL certificate expires in 30 days for {{ $labels.instance }} \n"
          summary: "SSL certificate expiry > 30 days\n"
      
      - alert: SslCertificateExpired
        expr: probe_ssl_earliest_cert_expiry - time()  <= 0
        for: 2m
        labels:
          severity: error
        annotations:
          description: "SSL certificate has expired for {{ $labels.instance }}\n"
          summary: "SSL Certificate is Expired \n"
  
  