global:
  scrape_interval:     15s
  evaluation_interval: 15s

  external_labels:
    monitor: 'promswarm'

rule_files:
  - "/etc/prometheus/*.yml"


alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: blackbox
    metrics_path: /probe
    relabel_configs: 
      - source_labels: 
          - __address__
        target_label: __param_target

      - source_labels: 
          - __param_target
        target_label: instance

      - replacement: "blackbox-exporter:9115"
        target_label: __address__
        
    scrape_interval: 120s
    file_sd_configs: 
      - files: 
          - "blackbox/targets.yml"

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'traefik-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.traefikv2'
      type: 'A'
      port: 8082

